#! /bin/bash

echo "Hi! Please make sure ./tt.pdf is the latest timetable"

echo "Starting process..."
echo "checking java installation"
java --version
echo "if you see java version information, you are good to go, else install openjdk11"

[[ -f "./tabula-jar.jar" ]] || (echo "downloading tabular-jar" && curl -#L "https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar" -o tabula-jar.jar)

echo "getting data"

table="$(java -jar tabula-jar.jar tt.pdf -gl | sed "s/\r/|/g" | cut -d, -f2,4,6,8,10,12 | sed "s/\"//g" | tail)"

echo "$table"

echo "$table" | python3 makeindex.py
